### ISSUE TITLE
Login UNPW?

### ISSUE THREAD

**Issue by sneedster** [wowstack/docker-classic-server#4]
Sorry, this isn't really an issue per se, but nowhere can I find any indication as to what username/password I can use to actually log into the game with a client. Nor any way to create one...I'm sure I am just missing something obvious, as nobody else seems to have any issues with this.

**Comment by pmdcosta** [comment]
Cant seem to find it either

**Comment by danielsreichenbach** [comment]
Correct, this is not documented since I just assumed people were used to the defaults.

The provided users are

- `ADMINISTRATOR` with password `ADMINISTRATOR`
- `GAMEMASTER` with password `GAMEMASTER`
- `MODERATOR` with password `MODERATOR`
- `PLAYER` with password `PLAYER`

**Comment by maidemao** [comment]
Is there any way to add new players?

**Comment by danielsreichenbach** [comment]
You can always change any user password in-game using `.account set password ACCOUTNAME PASSWORD`, create new accounts using `.account create ACCOUNTNAME`, and remove accounts using `.account delete ACCOUNTNAME`.
